### ISSUE TITLE
Conrtributing.md missing

### ISSUE THREAD

**Issue by Sidd2024** [solomonshalom/F1-Championship-Stats#1]
According to the hacktoberfest guidelines, there should be an contributing.md file with contribution guidelines in repositories participating in hacktoberfest.

Please assign this task to me!

**Comment by solomonshalom** [comment]
> According to the hacktoberfest guidelines, there should be an contributing.md file with contribution guidelines in repositories participating in hacktoberfest.
> 
> Please assign this task to me!

Sure! Please go ahead.

**Comment by Sidd2024** [comment]
here, I've raised a PR #2

**Comment by solomonshalom** [comment]
Ah, Thanks!
